kind = "web"
previewPath = "/aniyomi-website/"
title = "Aniyomi Website"
version = "1.0.0"
id = "artifacts/aniyomi-website"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/aniyomi-website/" ]
localPort = 20997

[services.development]
run = "pnpm --filter @workspace/aniyomi-website run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/aniyomi-website", "run", "build" ]
publicDir = "artifacts/aniyomi-website/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20997"
BASE_PATH = "/aniyomi-website/"
